### ISSUE TITLE
pageArray.loadedElements - Array index out of range when the last page is not fully loaded with elements

### ISSUE THREAD

**Issue by alejandrogarin** [MrAlek/PagedArray#5]
This is the test:

func testLoadedElementsForOnePageAndAHalfOfTheLastOne() {
        var tinyArray: PagedArray<Int> = PagedArray(count: 15, pageSize: 10)
        tinyArray.setElements(Array(0...9), page: 0)
        tinyArray.setElements(Array(10...11), page: 1)
        XCTAssertEqual(tinyArray.loadedElements.count, 12, "Array total count is not correct")
}

**Comment by MrAlek** [comment]
Thanks for setting up the issue.

I've been thinking about what to do with the last page, if it should be treated like all the others and require correct sizing or not. Since the array will mostly be used with a paging web service, the total count might differ from when you load the first page and you get the last.

What do you think, should I enforce correct sizing or make the array compensate on the last page itself?

**Comment by alejandrogarin** [comment]
I would not enforce the size in last page. 
I came across this issue when adding a few methods to reorder, insert and delete elements in the array so I don't need to reload all the pages again.
I applied a local fix looping through the pages and collecting the elements.
I think that just returning the loaded elements avoiding the crash is good enough.

**Comment by MrAlek** [comment]
I've taken a different take on this now (3c7001142a103b0d17859e0f13b643e7d4a5c365). In the 0.2 version, you have two options:

1. Adjust the `count` property on the paged array before setting the mis-sized page.
2. Set the `updatesCountWhenSettingPages` property to `true`, which removes all page size checking and dynamically adjusts the paged array to fit. That also makes infinite lists easy to implement since you can just append new pages.
